### ISSUE TITLE
Snapchat Stretch Bug

### ISSUE THREAD

**Issue by nareddyt** [PeterCxy/Lolistat#1]
When this module is enabled and used with Snapchat, the app seems to run in immersive mode. The notification bar becomes non-existent, and the Snapchat app stretches vertically to fill the entire screen, distorting the image. This does not happen with the stock camera app though, only with the Snapchat app.

Device: Nexus 4
ROM: Stock Lollipop 5.0.1
Installed the Alpha version of Xposed.

Other than this, every other app seems to be working fine!

**Comment by kylepsp** [comment]
Came here to post this, exactly the same issue, makes using the buttons at the bottom difficult also as the capture button and such go behind the navbar. 

Device Moto X 2014
ROM stock lollipop
Alpha Xposed

Perfect otherwise! Post an XDA thread to get this out there!
![image](https://cloud.githubusercontent.com/assets/11165932/6336729/88a5f1c4-bb9c-11e4-80f7-733bbba3f387.png)

**Comment by kylepsp** [comment]
Still not fixed for me

**Comment by nareddyt** [comment]
Yup... Workaround is that you can disable Lolistat for snapchat using the new UI.

**Comment by HiFIi** [comment]
Yep. I recommend just blacklisting it
